[section.admin]
title = "admin"
icon = "ri-user-settings-line"

[[section.admin.item]]
title = "192.168.10.1"
icon = "ri-router-line"
url = "http://192.168.10.1/"

[[section.admin.item]]
title = "Arch News"
icon = "ri-qq-line"
url = "https://archlinux.org/"

[[section.admin.item]]
title = "Arch Wiki"
icon = "ri-qq-line"
url = "https://wiki.archlinux.org/"

[[section.admin.item]]
title = "Beets"
icon = "ri-music-2-line"
url = "https://beets.readthedocs.io/"

[[section.admin.item]]
title = "btrfs"
icon = "ri-hard-drive-3-line"
url = "https://btrfs.readthedocs.io/en/latest/"

[[section.admin.item]]
title = "myip.ru"
icon = "ri-global-line"
url = "https://myip.ru/"

[[section.admin.item]]
title = "Tailscale"
icon = "ri-router-line"
url = "https://login.tailscale.com/admin"
