[sections.admin]
title = "admin"
icon = "ri-user-settings-line"

[[sections.admin.items]]
title = "192.168.10.1"
icon = "ri-router-line"
url = "http://192.168.10.1/"

[[sections.admin.items]]
title = "Arch Wiki"
icon = "ri-qq-line"
url = "https://wiki.archlinux.org/"

[[sections.admin.items]]
title = "Arch Packages"
icon = "ri-qq-line"
url = "https://archlinux.org/packages/"

[[sections.admin.items]]
title = "AUR"
icon = "ri-qq-line"
url = "https://aur.archlinux.org/"

[[sections.admin.items]]
title = "Beets"
icon = "ri-music-2-line"
url = "https://beets.io/"

[[sections.admin.items]]
title = "btrfs"
icon = "ri-hard-drive-3-line"
url = "https://btrfs.readthedocs.io/en/latest/"

[[sections.admin.items]]
title = "myip.ru"
icon = "ri-global-line"
url = "https://myip.ru/"
