[sections.bookmarks]
title = "bookmarks"
icon = "ri-bookmark-fill"

[[sections.bookmarks.items]]
title = "iliazeus.github.io"
icon = "ri-global-line"
url = "https://iliazeus.github.io/"

[[sections.bookmarks.items]]
title = "emojis.wiki"
icon = "ri-emoji-sticker-line"
url = "https://emojis.wiki/"

[[sections.bookmarks.items]]
title = "FoodData Central"
icon = "ri-scales-2-line"
url = "https://fdc.nal.usda.gov/fdc-app.html#/"

[[sections.bookmarks.items]]
title = "http-prompt"
icon = "ri-global-line"
url = "https://docs.http-prompt.com/en/latest/user-guide.html"

[[sections.bookmarks.items]]
title = "httpie"
icon = "ri-global-line"
url = "https://httpie.io/docs/cli"

[[sections.bookmarks.items]]
title = "kaz-tili.kz"
icon = "ri-kakao-talk-line"
url = "https://kaz-tili.kz/"

[[sections.bookmarks.items]]
title = "Remix Icons"
icon = "ri-remixicon-line"
url = "https://remixicon.com/"

[[sections.bookmarks.items]]
title = "Proton Mail"
icon = "ri-mail-line"
url = "https://mail.proton.me/"

[[sections.bookmarks.items]]
title = "Yandex Mail"
icon = "ri-mail-line"
url = "https://mail.yandex.ru/lite/"
