[section.e11t]
title = "e11t"
icon = "ri-cake-3-fill"

[[section.e11t.item]]
title = "anilibria.top"
icon = "ri-tv-line"
url = "https://anilibria.top/anime/releases/latest/"

[[section.e11t.item]]
title = "Habr"
icon = "ri-heading"
url = "https://habr.com/ru/all/"

[[section.e11t.item]]
title = "Kaboom"
icon = "ri-gamepad-line"
url = "https://pwmarcz.pl/kaboom/"

[[section.e11t.item]]
title = "lor.sh"
icon = "ri-mastodon-line"
url = "https://lor.sh/"

[[section.e11t.item]]
title = "Monkeytype"
icon = "ri-keyboard-line"
url = "https://monkeytype.com/"

[[section.e11t.item]]
title = "Reddit"
icon = "ri-reddit-line"
url = "https://reddit.com/"

[[section.e11t.item]]
title = "RuTracker.org"
icon = "ri-download-2-line"
url = "https://rutracker.org/forum/index.php"

[[section.e11t.item]]
title = "Steam"
icon = "ri-steam-line"
url = "https://store.steampowered.com/"

[[section.e11t.item]]
title = "tetr.io"
icon = "ri-gamepad-line"
url = "https://tetr.io/"

[[section.e11t.item]]
title = "Wallabag"
icon = "ri-git-repository-line"
url = "https://app.wallabag.it/"

[[section.e11t.item]]
title = "Random Unread"
icon = "ri-git-repository-line"
url = "https://app.wallabag.it/unread/random"

[[section.e11t.item]]
title = "Wikipedia"
icon = "ri-book-read-line"
url = "https://en.wikipedia.org/wiki/Main_Page"

[[section.e11t.item]]
title = "xkcd"
icon = "ri-group-line"
url = "https://xkcd.com/"

[[section.e11t.item]]
title = "YouTube"
icon = "ri-youtube-line"
url = "https://youtube.com/"

[[section.e11t.item]]
title = "YouTube Music"
icon = "ri-youtube-line"
url = "https://music.youtube.com/"
