[sections.games]
title = "games"
icon = "ri-game-fill"

[[sections.games.items]]
title = "Kaboom"
icon = "ri-gamepad-line"
url = "https://pwmarcz.pl/kaboom/"

[[sections.games.items]]
title = "Monkeytype"
icon = "ri-keyboard-line"
url = "https://monkeytype.com/"

[[sections.games.items]]
title = "Steam"
icon = "ri-steam-line"
url = "https://store.steampowered.com/"

[[sections.games.items]]
title = "tetr.io"
icon = "ri-gamepad-line"
url = "https://tetr.io/"
