[sections.repos]
title = "repos"
icon = "ri-box-3-fill"

[[sections.repos.items]]
title = "Arch Packages"
icon = "ri-qq-line"
url = "https://archlinux.org/packages/"

[[sections.repos.items]]
title = "AUR"
icon = "ri-qq-line"
url = "https://aur.archlinux.org/"

[[sections.repos.items]]
title = "crates.io"
icon = "ri-box-3-line"
url = "https://crates.io/"

[[sections.repos.items]]
title = "Docker Hub"
icon = "ri-instance-line"
url = "https://hub.docker.com/search?q="

[[sections.repos.items]]
title = "GitHub"
icon = "ri-github-line"
url = "https://github.com/"

[[sections.repos.items]]
title = "NPM"
icon = "ri-npmjs-line"
url = "https://www.npmjs.com/"

[[sections.repos.items]]
title = "Printables"
icon = "ri-pencil-ruler-line"
url = "https://printables.com/"

[[sections.repos.items]]
title = "PyPI"
icon = "ri-box-3-line"
url = "https://pypi.org/"
