[sections.tools]
title = "tools"
icon = "ri-tools-fill"

[[sections.tools.items]]
title = "crontab.guru"
icon = "ri-time-line"
url = "https://crontab.guru/"

[[sections.tools.items]]
title = "emojis.wiki"
icon = "ri-emoji-sticker-line"
url = "https://emojis.wiki/"

[[sections.tools.items]]
title = "jwt.io"
icon = "ri-key-line"
url = "https://jwt.io/"

[[sections.tools.items]]
title = "myip.ru"
icon = "ri-global-line"
url = "https://myip.ru/"

[[sections.tools.items]]
title = "node.green"
icon = "ri-javascript-line"
url = "https://node.green/"

[[sections.tools.items]]
title = "Remix Icons"
icon = "ri-remixicon-line"
url = "https://remixicon.com/"

[[sections.tools.items]]
title = "TS Playground"
icon = "ri-javascript-line"
url = "https://www.typescriptlang.org/play/"

[[sections.tools.items]]
title = "speedscope"
icon = "ri-microscope-line"
url = "https://www.speedscope.app/"

[[sections.tools.items]]
title = "Tinkercad"
icon = "ri-pencil-ruler-line"
url = "https://tinkercad.com/"

[[sections.tools.items]]
title = "TRONSCAN"
icon = "ri-bit-coin-line"
url = "https://tronscan.org/"
